artifacts_root: artifacts

# artifacts: The base directory where all output files generated during the project execution will be stored. 
# This directory helps in organizing and managing the different outputs produced at various stages of the pipeline.


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Mageshwaran18/Data_Sets/raw/main/Music_Popularity_Prediction_Data_Set.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion